### ISSUE TITLE
yaml

### ISSUE THREAD

**Issue by ssolson** [Data-Only-Greater/SNL-Delft3D-CEC-Verify#8]
Hey Mat,

I pulled your latest commits. It failed on a yaml import. So I `conda install yaml` but that didn't seem to fix the issue. Is there some other way I need to add this to the environment?
```
(_snld3d) C:\Users\sterl\Codes\SNL-Delft3D-CEC-Verify>conda install yaml
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\sterl\anaconda3\envs\_snld3d

  added / updated specs:
    - yaml


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    yaml-0.2.5                 |       h8ffe710_2          62 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          62 KB

The following NEW packages will be INSTALLED:

  yaml               conda-forge/win-64::yaml-0.2.5-h8ffe710_2


Proceed ([y]/n)? y


Downloading and Extracting Packages
yaml-0.2.5           | 62 KB     | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(_snld3d) C:\Users\sterl\Codes\SNL-Delft3D-CEC-Verify>cd examples

(_snld3d) C:\Users\sterl\Codes\SNL-Delft3D-CEC-Verify\examples>python basic.py
Traceback (most recent call last):
  File "C:\Users\sterl\Codes\SNL-Delft3D-CEC-Verify\examples\basic.py", line 11, in <module>
    from snl_d3d_cec_verify import CaseStudy, Report, Result, Runner, Template
  File "c:\users\sterl\codes\snl-delft3d-cec-verify\src\snl_d3d_cec_verify\__init__.py", line 5, in <module>
    from .result import Result, Validate
  File "c:\users\sterl\codes\snl-delft3d-cec-verify\src\snl_d3d_cec_verify\result\__init__.py", line 26, in <module>
    from yaml import load
ModuleNotFoundError: No module named 'yaml'
```

**Comment by H0R5E** [comment]
Sterling I recommend that you delete and rebuild the environment. I switched to conda-forge to get Python version 3.9.9 (to get the doctests to work), so recreating the environment is the only way you'll get it matching.

High up on the TODO list is making this easier to install and update.

**Comment by H0R5E** [comment]
Sterling, there are instructions for installing from a conda package [here](https://github.com/Data-Only-Greater/SNL-Delft3D-CEC-Verify#quick-start) now, so I'm going to close this.
